// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDftJ6t10klyJ5-miCqknmYaAX9VZ_-ZjI',
    appId: '1:632822449676:android:d54ba3ab032eb3eae49029',
    messagingSenderId: '632822449676',
    projectId: 'rowchem-4c7a3',
    databaseURL: 'https://rowchem-4c7a3-default-rtdb.firebaseio.com',
    storageBucket: 'rowchem-4c7a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc-eTsp--DInjx20VBYbPDNvoetc8AkaQ',
    appId: '1:632822449676:ios:573ad5e0d4fdc9ade49029',
    messagingSenderId: '632822449676',
    projectId: 'rowchem-4c7a3',
    databaseURL: 'https://rowchem-4c7a3-default-rtdb.firebaseio.com',
    storageBucket: 'rowchem-4c7a3.firebasestorage.app',
    iosClientId: '632822449676-vo1vc91uk5u93mhuhiodnito3lj8rloa.apps.googleusercontent.com',
    iosBundleId: 'com.example.rawChem',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUjsahqnYVYM_m99Ey1tm54XK8v7MZ72M',
    appId: '1:632822449676:web:571d777317c2fc58e49029',
    messagingSenderId: '632822449676',
    projectId: 'rowchem-4c7a3',
    authDomain: 'rowchem-4c7a3.firebaseapp.com',
    databaseURL: 'https://rowchem-4c7a3-default-rtdb.firebaseio.com',
    storageBucket: 'rowchem-4c7a3.firebasestorage.app',
    measurementId: 'G-PH5LYWXB40',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc-eTsp--DInjx20VBYbPDNvoetc8AkaQ',
    appId: '1:632822449676:ios:573ad5e0d4fdc9ade49029',
    messagingSenderId: '632822449676',
    projectId: 'rowchem-4c7a3',
    databaseURL: 'https://rowchem-4c7a3-default-rtdb.firebaseio.com',
    storageBucket: 'rowchem-4c7a3.firebasestorage.app',
    iosClientId: '632822449676-vo1vc91uk5u93mhuhiodnito3lj8rloa.apps.googleusercontent.com',
    iosBundleId: 'com.example.rawChem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUjsahqnYVYM_m99Ey1tm54XK8v7MZ72M',
    appId: '1:632822449676:web:8db448cbb2bbb846e49029',
    messagingSenderId: '632822449676',
    projectId: 'rowchem-4c7a3',
    authDomain: 'rowchem-4c7a3.firebaseapp.com',
    databaseURL: 'https://rowchem-4c7a3-default-rtdb.firebaseio.com',
    storageBucket: 'rowchem-4c7a3.firebasestorage.app',
    measurementId: 'G-2N0FRD5PLR',
  );

}