// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRxUlP48VAK4SNHF4ufW_7aPx_YB2GixQ',
    appId: '1:365422018557:android:a4ba69dc6fd4196a7de394',
    messagingSenderId: '365422018557',
    projectId: 'authon-f466d',
    storageBucket: 'authon-f466d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYwHdnFLRNNCc5C-ToxGpqx5a5J3QECTA',
    appId: '1:365422018557:ios:33be6f093c13101d7de394',
    messagingSenderId: '365422018557',
    projectId: 'authon-f466d',
    storageBucket: 'authon-f466d.firebasestorage.app',
    androidClientId: '365422018557-a4186gprmsjqqv90tquvcqig46v1dfls.apps.googleusercontent.com',
    iosClientId: '365422018557-lqm85i01qq2lbvicc10r1p5r5gn269ri.apps.googleusercontent.com',
    iosBundleId: 'tech.brmja.cochizer',
  );

}
